services:
  jekyll:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    command: bundle exec jekyll serve --host 0.0.0.0

  bundle-update:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: bundle update